Version="1"

[[command]]
    isTemplate=true
    name="basic-php-command"
    entrypoint="php"
    removeContainer=true
    impersonate=true
    workDir="${PWD}"
    volumes=[
        "/tmp:/tmp",
        "/home/nils/PhpstormProjects/droxy-phpstorm-integration:/home/nils/PhpstormProjects/droxy-phpstorm-integration",
        "/home/nils:/home/nils"
    ]

[[command]]
    name="php7.2"
    image="php7.2"
    template="basic-php-command"
    envvars=[
        "XDEBUG_CONFIG=${XDEBUG_CONFIG}"
    ]
    replaceArgs=[
        [
            "-dxdebug.remote_host=127.0.0.1",
            "-dxdebug.remote_host=172.17.0.1",
        ]
    ]

[[command]]
    name="phpmd"
    image="php7.2"
    workDir="/home/nils/PhpstormProjects/droxy-phpstorm-integration"
    template="basic-php-command"
    command="vendor/bin/phpmd"

[[command]]
    name="phpcs"
    image="php7.2"
    workDir="/home/nils/PhpstormProjects/droxy-phpstorm-integration"
    template="basic-php-command"
    command="vendor/bin/phpcs"