Version="1"

[[command]]
    name="php7.2"
    image="php7.2"
    removeContainer=true
    volumes=[
        "/tmp:/tmp",
        "/home/nils/PhpstormProjects/droxy-phpstorm-integration:/home/nils/PhpstormProjects/droxy-phpstorm-integration"
    ]
    replaceArgs=[
        [
            "-dxdebug.remote_host=127.0.0.1",
            "-dxdebug.remote_host=172.17.0.1",
        ]
    ]