Version="1"

[[command]]
    name="php7.2"
    image="php7.2"
    removeContainer=true
    volumes=[
        "/tmp:/tmp",
        "/home/nils/PhpstormProjects/droxy-phpstorm-integration:/home/nils/PhpstormProjects/droxy-phpstorm-integration"
    ]